service: rds-automation

custom:
  stage: ${opt:stage, self:provider.stage}
  clusterName: ${opt:clusterName}
  clusterArn: ${opt:clusterArn}

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"
    - Effect: "Allow"
      Action:
        - "rds:StartDBCluster"
        - "rds:StopDBCluster"
        - "rds:DescribeDBClusters"
      Resource:
        - ${self:custom.clusterArn}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  rdsAutomation:
    handler: bin/main
    events:
      - eventBridge:
          schedule: cron(0,2 12 ? * TUE,FRI *) # 日本時間の11時と20時
          # input:
    environment:
     CLUSTER_NAME: ${self:custom.clusterName}
